rename option cut video to trim change extension output video file

diff --git a/convertToH264 b/convertToH264
--- a/convertToH264
+++ b/convertToH264
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-PREFIX="_i.mp4"
+PREFIX=".mp4"
 
 # A POSIX variable
 OPTIND=1         # Reset in case getopts has been used previously in the shell.
@@ -11,8 +11,10 @@ show_help() {
 Usage: convertToH264 [OPTIONS] [FILE]... 
  
     -h	        Show help
+    -r          Remove audio
     -s FORMAT   Scale (resize) the input video, format: "240", "360", "480", "720", "1080"
-    -c SECONDS  Cut first SECONDS of video
+    -t TIME     Trim the input video starting from TIME, TIME format is: hh:mm:ss
+    
 EOF
 }
 
@@ -20,23 +22,29 @@ if [ $# -eq 0 ]; then
     show_help 
 fi
 
-while getopts ":hs:c:" opt; do
+audio_filter="-c:a aac -strict -2"
+
+while getopts ":hrs:t:" opt; do
     case $opt in
-	s)
-            if [[ $FORMATS == *$OPTARG* ]]; then
-	        video_filter="-vf scale=-2:$OPTARG"
-		PREFIX="_$OPTARG"p.mp4
-            else
-            	echo "Invalid video format: $OPTARG" >&2
-		exit 1
-            fi
-      	    ;;
-        c)
-	    cut_seconds="-ss $OPTARG"
-	    ;;
         h)
             show_help
-	    exit 0
+            exit 0
+            ;;
+        r)
+            audio_filter="-an"
+            PREFIX="_na$PREFIX"
+            ;;
+        s)
+            if [[ $FORMATS == *$OPTARG* ]]; then
+                video_filter="-vf scale=-2:$OPTARG"
+                PREFIX="_$OPTARG"p"$PREFIX"
+            else
+            	echo "Invalid video format: $OPTARG" >&2
+		        exit 1
+            fi
+      	    ;;
+        t)
+            trim_time="-ss $OPTARG"
             ;;
     	\?)
       	    echo "Invalid option: -$OPTARG" >&2
@@ -54,5 +62,6 @@ shift "$((OPTIND-1))"
 for i in "$@"; do
     input_file=$(realpath "$i")
     out_file="$input_file$PREFIX"
-    ffmpeg -i "$input_file" $video_filter -c:v libx264 -profile:v high -level 4.2 -c:a aac -strict -2 $cut_seconds "$out_file"
+    ffmpeg -i "$input_file" $video_filter -c:v libx264 -profile:v high -level 4.2 $audio_filter $trim_time "$out_file"
 done
+
